-- Create PLAYER table
CREATE TABLE IF NOT EXISTS PLAYER (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    COLOR BOOLEAN NOT NULL
);

-- Create MATCH table
CREATE TABLE IF NOT EXISTS GAME (
    ID SERIAL PRIMARY KEY,
    IS_FINISHED BOOLEAN NOT NULL,
    PLAYER_ID INTEGER REFERENCES PLAYER(ID),
    MOVE_HISTORY TEXT,
    TURN BOOLEAN NOT NULL,
    BOARD CHAR(8)[][] -- Add the new column for the board
);

-- Create ROOM table
CREATE TABLE IF NOT EXISTS ROOM (
    ID VARCHAR(50) PRIMARY KEY,
    GAME_ID INTEGER REFERENCES GAME(ID),
    AMOUNT_PLAYER INTEGER DEFAULT 0 -- Add the new column with a default value of 0
);

-- Create MATCH_HISTORY table
CREATE TABLE IF NOT EXISTS MATCH_HISTORY (
    ID SERIAL PRIMARY KEY,
    GAME_ID INTEGER REFERENCES GAME(ID),
    MOVE_NUMBER INTEGER NOT NULL,
    MOVE_DETAILS TEXT
);
